language: csharp

os:
  - linux
  - osx

solution: AmazonStorageLatency.sln
mono:
  - latest
install:
  - sudo apt-get install -y sysbench
  - nuget restore $TRAVIS_SOLUTION
script:
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Release /verbosity:minimal
  - if test "$TRAVIS_OS_NAME" == "linux"; then
       cat /proc/cpuinfo;
       bash travis-plugins/show-perfomance.sh;
    fi

  